language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 

addons:
    ssh_known_hosts: 39.108.125.0
script:
- npm run build
after_script:
# - ssh root@39.108.125.0 "./data/travis" # 请替换成自己的登录IP和登录用户
- scp -o stricthostkeychecking=no -r dist root@39.108.125.0:/data/travis
branches:
  only:
  - master
env:
  global: 
before_install:
- openssl aes-256-cbc -K $encrypted_5f4d1625ed6b_key -iv $encrypted_5f4d1625ed6b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 39.108.125.0\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
